apiVersion: v1
kind: Service
metadata:
  name: ts-admin-order-service
  labels:
    app: ts-admin-order-service
spec:
  ports:
    - port: 16112
      name: http
  selector:
    app: ts-admin-order-service