apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-food-map-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-food-map-service
        version: v1
    spec:
      containers:
      - name: ts-food-map-service
        image: ts/ts-food-map-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 18855