apiVersion: v1
kind: Service
metadata:
  name: ts-notification-service
  labels:
    app: ts-notification-service
spec:
  ports:
    - port: 17853
      name: http
  selector:
    app: ts-notification-service