apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-mongo
  labels:
    app: ts-order-other-mongo
spec:
  ports:
    - port: 27017
      name: mongo
  selector:
    app: ts-order-other-mongo