apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-voucher-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-voucher-mysql
        version: v1
    spec:
      containers:
      - name: ts-voucher-mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        env:
        # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306