apiVersion: v1
kind: Service
metadata:
  name: ts-admin-travel-service
  labels:
    app: ts-admin-travel-service
spec:
  ports:
    - port: 16114
      name: http
  selector:
    app: ts-admin-travel-service