apiVersion: v1
kind: Service
metadata:
  name: ts-ticketinfo-service
  labels:
    app: ts-ticketinfo-service
spec:
  ports:
    - port: 15681
      name: http
  selector:
    app: ts-ticketinfo-service