apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogue-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogue-db
        version: v1
    spec:
      containers:
      - name: catalogue-db
        image: weaveworksdemos/catalogue-db:0.3.0
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: fake_password
          - name: MYSQL_DATABASE
            value: socksdb
        ports:
        - name: mysql
          containerPort: 3306
