apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-service
  labels:
    app: ts-order-other-service
spec:
  ports:
    - port: 12032
      name: http
  selector:
    app: ts-order-other-service