apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-food-map-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-food-map-mongo
        version: v1
    spec:
      containers:
      - name: ts-food-map-mongo
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017