apiVersion: v1
kind: Service
metadata:
  name: ts-sso-service
  labels:
    app: ts-sso-service
spec:
  type: NodePort
  ports:
    - port: 12349
      name: http
      nodePort: 30003
  selector:
    app: ts-sso-service