apiVersion: v1
kind: Service
metadata:
  name: ts-inside-payment-service
  labels:
    app: ts-inside-payment-service
spec:
  ports:
    - port: 18673
      name: http
  selector:
    app: ts-inside-payment-service