/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.ac.iscas.cloudeploy.rmi.entity;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ActionTyped implements org.apache.thrift.TEnum {
  CREATE(0),
  UPDATE(1),
  DELETE(2),
  SERVICE_START(3),
  SERVICE_STOP(4),
  SERVICE_RESTART(5);

  private final int value;

  private ActionTyped(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ActionTyped findByValue(int value) { 
    switch (value) {
      case 0:
        return CREATE;
      case 1:
        return UPDATE;
      case 2:
        return DELETE;
      case 3:
        return SERVICE_START;
      case 4:
        return SERVICE_STOP;
      case 5:
        return SERVICE_RESTART;
      default:
        return null;
    }
  }
}
