apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogue
        version: v1
    spec:
      containers:
      - name: catalogue
        image: weaveworksdemos/catalogue:0.3.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
