apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders-db
        version: v1
    spec:
      containers:
      - name: orders-db
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
