apiVersion: v1
kind: Service
metadata:
  name: ts-consign-price-service
  labels:
    app: ts-consign-price-service
spec:
  ports:
    - port: 16110
      name: http
  selector:
    app: ts-consign-price-service