apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: queue-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: queue-master
        version: v1
    spec:
      containers:
      - name: queue-master
        image: weaveworksdemos/queue-master:0.3.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
