apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-db
        version: v1
    spec:
      containers:
      - name: user-db
        image: weaveworksdemos/user-db:0.4.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory