apiVersion: v1
kind: Service
metadata:
  name: ts-admin-basic-info-service
  labels:
    app: ts-admin-basic-info-service
spec:
  ports:
    - port: 18767
      name: http
  selector:
    app: ts-admin-basic-info-service