apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-other-service
  labels:
    app: ts-preserve-other-service
spec:
  ports:
    - port: 14569
      name: http
  selector:
    app: ts-preserve-other-service