apiVersion: v1
kind: Service
metadata:
  name: ts-travel-plan-service
  labels:
    app: ts-travel-plan-service
spec:
  ports:
    - port: 14322
      name: http
  selector:
    app: ts-travel-plan-service