apiVersion: v1
kind: Service
metadata:
  name: ts-admin-route-service
  labels:
    app: ts-admin-route-service
spec:
  ports:
    - port: 16113
      name: http
  selector:
    app: ts-admin-route-service