apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user
        version: v1
    spec:
      containers:
      - name: user
        image: weaveworksdemos/user:0.4.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: user-db:27017
