apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        version: v1
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
