apiVersion: v1
kind: Service
metadata:
  name: ts-route-plan-service
  labels:
    app: ts-route-plan-service
spec:
  ports:
    - port: 14578
      name: http
  selector:
    app: ts-route-plan-service