apiVersion: v1
kind: Service
metadata:
  name: ts-ticket-office-service
  labels:
    app: ts-ticket-office-service
spec:
  ports:
    - port: 16108
      name: http
  selector:
    app: ts-ticket-office-service