--- 
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::bindings::client_dev"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::bindings::daemon_dev"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::bindings::java"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::bindings::perl"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::bindings::php"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::bindings::python"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::bindings::ruby"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::bindings"
    type: !ruby/sym hostclass
    params: 
      java_enable: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 4
          file: 
          value: false
      perl_enable: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 5
          file: 
          value: false
      php_enable: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 6
          file: 
          value: false
      python_enable: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 7
          file: 
          value: false
      ruby_enable: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 8
          file: 
          value: false
      client_dev: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 9
          file: 
          value: false
      daemon_dev: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 10
          file: 
          value: false
      java_package_ensure: 
        value: "${$mysql::params::java_package_ensure}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 12
          file: 
          value: "mysql::params::java_package_ensure"
      java_package_name: 
        value: "${$mysql::params::java_package_name}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 13
          file: 
          value: "mysql::params::java_package_name"
      java_package_provider: 
        value: "${$mysql::params::java_package_provider}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 14
          file: 
          value: "mysql::params::java_package_provider"
      perl_package_ensure: 
        value: "${$mysql::params::perl_package_ensure}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 15
          file: 
          value: "mysql::params::perl_package_ensure"
      perl_package_name: 
        value: "${$mysql::params::perl_package_name}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 16
          file: 
          value: "mysql::params::perl_package_name"
      perl_package_provider: 
        value: "${$mysql::params::perl_package_provider}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 17
          file: 
          value: "mysql::params::perl_package_provider"
      php_package_ensure: 
        value: "${$mysql::params::php_package_ensure}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 18
          file: 
          value: "mysql::params::php_package_ensure"
      php_package_name: 
        value: "${$mysql::params::php_package_name}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 19
          file: 
          value: "mysql::params::php_package_name"
      php_package_provider: 
        value: "${$mysql::params::php_package_provider}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 20
          file: 
          value: "mysql::params::php_package_provider"
      python_package_ensure: 
        value: "${$mysql::params::python_package_ensure}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 21
          file: 
          value: "mysql::params::python_package_ensure"
      python_package_name: 
        value: "${$mysql::params::python_package_name}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 22
          file: 
          value: "mysql::params::python_package_name"
      python_package_provider: 
        value: "${$mysql::params::python_package_provider}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 23
          file: 
          value: "mysql::params::python_package_provider"
      ruby_package_ensure: 
        value: "${$mysql::params::ruby_package_ensure}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 24
          file: 
          value: "mysql::params::ruby_package_ensure"
      ruby_package_name: 
        value: "${$mysql::params::ruby_package_name}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 25
          file: 
          value: "mysql::params::ruby_package_name"
      ruby_package_provider: 
        value: "${$mysql::params::ruby_package_provider}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 26
          file: 
          value: "mysql::params::ruby_package_provider"
      client_dev_package_ensure: 
        value: "${$mysql::params::client_dev_package_ensure}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 27
          file: 
          value: "mysql::params::client_dev_package_ensure"
      client_dev_package_name: 
        value: "${$mysql::params::client_dev_package_name}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 28
          file: 
          value: "mysql::params::client_dev_package_name"
      client_dev_package_provider: 
        value: "${$mysql::params::client_dev_package_provider}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 29
          file: 
          value: "mysql::params::client_dev_package_provider"
      daemon_dev_package_ensure: 
        value: "${$mysql::params::daemon_dev_package_ensure}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 30
          file: 
          value: "mysql::params::daemon_dev_package_ensure"
      daemon_dev_package_name: 
        value: "${$mysql::params::daemon_dev_package_name}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 31
          file: 
          value: "mysql::params::daemon_dev_package_name"
      daemon_dev_package_provider: 
        value: "${$mysql::params::daemon_dev_package_provider}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 32
          file: 
          value: "mysql::params::daemon_dev_package_provider"
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::client::install"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::client"
    type: !ruby/sym hostclass
    params: 
      bindings_enable: 
        value: "${$mysql::params::bindings_enable}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 3
          file: 
          value: "mysql::params::bindings_enable"
      package_ensure: 
        value: "${$mysql::params::client_package_ensure}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 4
          file: 
          value: "mysql::params::client_package_ensure"
      package_name: 
        value: "${$mysql::params::client_package_name}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 5
          file: 
          value: "mysql::params::client_package_name"
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::db"
    type: !ruby/sym definition
    params: 
      user: 
        value: 
        type: 
      password: 
        value: 
        type: 
      dbname: 
        value: "${$name}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 5
          file: 
          value: name
      charset: 
        value: utf8
        type: !ruby/object:Puppet::Parser::AST::String
          line: 6
          file: 
          value: utf8
      collate: 
        value: utf8_general_ci
        type: !ruby/object:Puppet::Parser::AST::String
          line: 7
          file: 
          value: utf8_general_ci
      host: 
        value: localhost
        type: !ruby/object:Puppet::Parser::AST::String
          line: 8
          file: 
          value: localhost
      grant: 
        value: ALL
        type: !ruby/object:Puppet::Parser::AST::String
          line: 9
          file: 
          value: ALL
      sql: 
        value: undef
        type: !ruby/object:Puppet::Parser::AST::Undef
          line: 10
          file: 
          value: !ruby/sym undef
      enforce_sql: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 11
          file: 
          value: false
      ensure: 
        value: present
        type: !ruby/object:Puppet::Parser::AST::String
          line: 12
          file: 
          value: present
      import_timeout: 
        value: 300
        type: !ruby/object:Puppet::Parser::AST::Name
          line: 13
          file: 
          value: "300"
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::params"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::server::account_security"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::server::backup"
    type: !ruby/sym hostclass
    params: 
      backupuser: 
        value: 
        type: 
      backuppassword: 
        value: 
        type: 
      backupdir: 
        value: 
        type: 
      backupdirmode: 
        value: "0700"
        type: !ruby/object:Puppet::Parser::AST::String
          line: 6
          file: 
          value: "0700"
      backupdirowner: 
        value: root
        type: !ruby/object:Puppet::Parser::AST::String
          line: 7
          file: 
          value: root
      backupdirgroup: 
        value: root
        type: !ruby/object:Puppet::Parser::AST::String
          line: 8
          file: 
          value: root
      backupcompress: 
        value: true
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 9
          file: 
          value: true
      backuprotate: 
        value: 30
        type: !ruby/object:Puppet::Parser::AST::Name
          line: 10
          file: 
          value: "30"
      ignore_events: 
        value: true
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 11
          file: 
          value: true
      delete_before_dump: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 12
          file: 
          value: false
      backupdatabases: 
        value: []
        type: !ruby/object:Puppet::Parser::AST::ASTArray
          line: 13
          file: 
          children: []
      file_per_database: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 14
          file: 
          value: false
      ensure: 
        value: present
        type: !ruby/object:Puppet::Parser::AST::String
          line: 15
          file: 
          value: present
      time: 
        value: 
          - "23"
          - "5"
        type: !ruby/object:Puppet::Parser::AST::ASTArray
          line: 16
          file: 
          children: 
            - !ruby/object:Puppet::Parser::AST::String
              line: 16
              file: 
              value: "23"
            - !ruby/object:Puppet::Parser::AST::String
              line: 16
              file: 
              value: "5"
      postscript: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 17
          file: 
          value: false
      execpath: 
        value: "/usr/bin:/usr/sbin:/bin:/sbin"
        type: !ruby/object:Puppet::Parser::AST::String
          line: 18
          file: 
          value: "/usr/bin:/usr/sbin:/bin:/sbin"
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::server::config"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::server::install"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::server::monitor"
    type: !ruby/sym hostclass
    params: 
      mysql_monitor_username: 
        value: 
        type: 
      mysql_monitor_password: 
        value: 
        type: 
      mysql_monitor_hostname: 
        value: 
        type: 
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::server::mysqltuner"
    type: !ruby/sym hostclass
    params: 
      ensure: 
        value: present
        type: !ruby/object:Puppet::Parser::AST::String
          line: 2
          file: 
          value: present
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::server::providers"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::server::root_password"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::server::service"
    type: !ruby/sym hostclass
    params: {}
  - !ruby/object:Proxy::Puppet::PuppetClass
    klass: "mysql::server"
    type: !ruby/sym hostclass
    params: 
      config_file: 
        value: "${$mysql::params::config_file}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 3
          file: 
          value: "mysql::params::config_file"
      includedir: 
        value: "${$mysql::params::includedir}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 4
          file: 
          value: "mysql::params::includedir"
      manage_config_file: 
        value: "${$mysql::params::manage_config_file}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 5
          file: 
          value: "mysql::params::manage_config_file"
      old_root_password: 
        value: "${$mysql::params::old_root_password}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 6
          file: 
          value: "mysql::params::old_root_password"
      override_options: 
        value: {}
        type: !ruby/object:Puppet::Parser::AST::ASTHash
          line: 7
          file: 
          value: {}
      package_ensure: 
        value: "${$mysql::params::server_package_ensure}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 8
          file: 
          value: "mysql::params::server_package_ensure"
      package_name: 
        value: "${$mysql::params::server_package_name}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 9
          file: 
          value: "mysql::params::server_package_name"
      purge_conf_dir: 
        value: "${$mysql::params::purge_conf_dir}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 10
          file: 
          value: "mysql::params::purge_conf_dir"
      remove_default_accounts: 
        value: false
        type: !ruby/object:Puppet::Parser::AST::Boolean
          line: 11
          file: 
          value: false
      restart: 
        value: "${$mysql::params::restart}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 12
          file: 
          value: "mysql::params::restart"
      root_group: 
        value: "${$mysql::params::root_group}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 13
          file: 
          value: "mysql::params::root_group"
      root_password: 
        value: "${$mysql::params::root_password}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 14
          file: 
          value: "mysql::params::root_password"
      service_enabled: 
        value: "${$mysql::params::server_service_enabled}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 15
          file: 
          value: "mysql::params::server_service_enabled"
      service_manage: 
        value: "${$mysql::params::server_service_manage}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 16
          file: 
          value: "mysql::params::server_service_manage"
      service_name: 
        value: "${$mysql::params::server_service_name}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 17
          file: 
          value: "mysql::params::server_service_name"
      service_provider: 
        value: "${$mysql::params::server_service_provider}"
        type: !ruby/object:Puppet::Parser::AST::Variable
          line: 18
          file: 
          value: "mysql::params::server_service_provider"
      users: 
        value: {}
        type: !ruby/object:Puppet::Parser::AST::ASTHash
          line: 19
          file: 
          value: {}
      grants: 
        value: {}
        type: !ruby/object:Puppet::Parser::AST::ASTHash
          line: 20
          file: 
          value: {}
      databases: 
        value: {}
        type: !ruby/object:Puppet::Parser::AST::ASTHash
          line: 21
          file: 
          value: {}
      enabled: 
        value: undef
        type: !ruby/object:Puppet::Parser::AST::Undef
          line: 24
          file: 
          value: !ruby/sym undef
      manage_service: 
        value: undef
        type: !ruby/object:Puppet::Parser::AST::Undef
          line: 25
          file: 
          value: !ruby/sym undef
