apiVersion: v1
kind: Service
metadata:
  name: ts-verification-code-service
  labels:
    app: ts-verification-code-service
spec:
  ports:
    - port: 15678
      name: http
  selector:
    app: ts-verification-code-service
