/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.ac.iscas.cloudapp.agent.transaction;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PropagationEvent implements org.apache.thrift.TBase<PropagationEvent, PropagationEvent._Fields>, java.io.Serializable, Cloneable, Comparable<PropagationEvent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PropagationEvent");

  private static final org.apache.thrift.protocol.TField EVENT_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("eventKey", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField EVENT_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("eventValue", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PropagationEventStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PropagationEventTupleSchemeFactory());
  }

  public String eventKey; // required
  public String eventValue; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EVENT_KEY((short)1, "eventKey"),
    EVENT_VALUE((short)2, "eventValue");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EVENT_KEY
          return EVENT_KEY;
        case 2: // EVENT_VALUE
          return EVENT_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EVENT_KEY, new org.apache.thrift.meta_data.FieldMetaData("eventKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EVENT_VALUE, new org.apache.thrift.meta_data.FieldMetaData("eventValue", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PropagationEvent.class, metaDataMap);
  }

  public PropagationEvent() {
  }

  public PropagationEvent(
    String eventKey,
    String eventValue)
  {
    this();
    this.eventKey = eventKey;
    this.eventValue = eventValue;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PropagationEvent(PropagationEvent other) {
    if (other.isSetEventKey()) {
      this.eventKey = other.eventKey;
    }
    if (other.isSetEventValue()) {
      this.eventValue = other.eventValue;
    }
  }

  public PropagationEvent deepCopy() {
    return new PropagationEvent(this);
  }

  @Override
  public void clear() {
    this.eventKey = null;
    this.eventValue = null;
  }

  public String getEventKey() {
    return this.eventKey;
  }

  public PropagationEvent setEventKey(String eventKey) {
    this.eventKey = eventKey;
    return this;
  }

  public void unsetEventKey() {
    this.eventKey = null;
  }

  /** Returns true if field eventKey is set (has been assigned a value) and false otherwise */
  public boolean isSetEventKey() {
    return this.eventKey != null;
  }

  public void setEventKeyIsSet(boolean value) {
    if (!value) {
      this.eventKey = null;
    }
  }

  public String getEventValue() {
    return this.eventValue;
  }

  public PropagationEvent setEventValue(String eventValue) {
    this.eventValue = eventValue;
    return this;
  }

  public void unsetEventValue() {
    this.eventValue = null;
  }

  /** Returns true if field eventValue is set (has been assigned a value) and false otherwise */
  public boolean isSetEventValue() {
    return this.eventValue != null;
  }

  public void setEventValueIsSet(boolean value) {
    if (!value) {
      this.eventValue = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case EVENT_KEY:
      if (value == null) {
        unsetEventKey();
      } else {
        setEventKey((String)value);
      }
      break;

    case EVENT_VALUE:
      if (value == null) {
        unsetEventValue();
      } else {
        setEventValue((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case EVENT_KEY:
      return getEventKey();

    case EVENT_VALUE:
      return getEventValue();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case EVENT_KEY:
      return isSetEventKey();
    case EVENT_VALUE:
      return isSetEventValue();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PropagationEvent)
      return this.equals((PropagationEvent)that);
    return false;
  }

  public boolean equals(PropagationEvent that) {
    if (that == null)
      return false;

    boolean this_present_eventKey = true && this.isSetEventKey();
    boolean that_present_eventKey = true && that.isSetEventKey();
    if (this_present_eventKey || that_present_eventKey) {
      if (!(this_present_eventKey && that_present_eventKey))
        return false;
      if (!this.eventKey.equals(that.eventKey))
        return false;
    }

    boolean this_present_eventValue = true && this.isSetEventValue();
    boolean that_present_eventValue = true && that.isSetEventValue();
    if (this_present_eventValue || that_present_eventValue) {
      if (!(this_present_eventValue && that_present_eventValue))
        return false;
      if (!this.eventValue.equals(that.eventValue))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(PropagationEvent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetEventKey()).compareTo(other.isSetEventKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEventKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.eventKey, other.eventKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEventValue()).compareTo(other.isSetEventValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEventValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.eventValue, other.eventValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PropagationEvent(");
    boolean first = true;

    sb.append("eventKey:");
    if (this.eventKey == null) {
      sb.append("null");
    } else {
      sb.append(this.eventKey);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("eventValue:");
    if (this.eventValue == null) {
      sb.append("null");
    } else {
      sb.append(this.eventValue);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PropagationEventStandardSchemeFactory implements SchemeFactory {
    public PropagationEventStandardScheme getScheme() {
      return new PropagationEventStandardScheme();
    }
  }

  private static class PropagationEventStandardScheme extends StandardScheme<PropagationEvent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PropagationEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EVENT_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.eventKey = iprot.readString();
              struct.setEventKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EVENT_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.eventValue = iprot.readString();
              struct.setEventValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PropagationEvent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.eventKey != null) {
        oprot.writeFieldBegin(EVENT_KEY_FIELD_DESC);
        oprot.writeString(struct.eventKey);
        oprot.writeFieldEnd();
      }
      if (struct.eventValue != null) {
        oprot.writeFieldBegin(EVENT_VALUE_FIELD_DESC);
        oprot.writeString(struct.eventValue);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PropagationEventTupleSchemeFactory implements SchemeFactory {
    public PropagationEventTupleScheme getScheme() {
      return new PropagationEventTupleScheme();
    }
  }

  private static class PropagationEventTupleScheme extends TupleScheme<PropagationEvent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PropagationEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetEventKey()) {
        optionals.set(0);
      }
      if (struct.isSetEventValue()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetEventKey()) {
        oprot.writeString(struct.eventKey);
      }
      if (struct.isSetEventValue()) {
        oprot.writeString(struct.eventValue);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PropagationEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.eventKey = iprot.readString();
        struct.setEventKeyIsSet(true);
      }
      if (incoming.get(1)) {
        struct.eventValue = iprot.readString();
        struct.setEventValueIsSet(true);
      }
    }
  }

}

